#//
#//  .swiftlint.yml
#//  NGMacrosApp
#//
#//  Created by Mohd Shoeb on 08/08/23.
#//

disabled_rules:
- trailing_whitespace
- multiple_closures_with_trailing_closure

opt_in_rules:
- empty_count
- empty_string
- vertical_parameter_alignment_on_call
- multiline_parameters

excluded:
- Pods
#- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: false
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 40
    error: 50

function_parameter_count:
    warning: 4
    error: 6

type_body_length:
    warning: 300
    error: 350

file_length:
    warning: 400
    error: 450
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25
    
empty_count:
    only_after_dot: true

reporter: "xcode"

